export * as authAPI from './auth'
export * as petsAPI from './pets'
export * as appointmentsAPI from './appointments'
export * as adoptionAPI from './adoption'
export * as communityAPI from './community'
export * as emergencyAPI from './emergency'
export * as notificationsAPI from './notifications'
export * as dashboardAPI from './dashboard'
export { default as API } from './axios'
