# Generated by Django 6.0.3 on 2026-03-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='michrochip_id',
            new_name='microchip_id',
        ),
    ]
