# Generated by Django 6.0.3 on 2026-03-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('pets', '0002_rename_michrochip_id_pet_microchip_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
