# Generated by Django 6.0.3 on 2026-03-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_appointments_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableSolt',
            new_name='AvailableSlot',
        ),
    ]
